server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://microservices-db.c2hcw4woa2eq.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=order_schema
    username: postgres
    password: Pscr78k94k21k
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
# Configuration for Feign Client to call Product Service
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
