server:
  port: 8081 # Each service will have a different internal port
spring:
  datasource:
    url: jdbc:postgresql://microservices-db.c2hcw4woa2eq.us-east-1.rds.amazonaws.com:5432/postgres?currentSchema=user_schema
    username: postgres
    password: Pscr78k94k21k
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the database schema
    show-sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
