server:
  port: 8081 # Each service will have a different internal port
spring:
  datasource:
    url: jdbc:postgresql://<YOUR_RDS_ENDPOINT>:5432/postgres?currentSchema=user_schema
    username: <YOUR_DB_USERNAME>
    password: <YOUR_DB_PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the database schema
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
